services:
  kobuki:
    image: ghcr.io/airesearchlab/kobuki:humble
    command: ros2 launch kobuki kobuki.launch.py
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
      
  astra_legacy:
    image: ghcr.io/airesearchlab/astra_legacy:humble
    command: ros2 launch astra_camera astra_pro.launch.py
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev